-- Nexium PalBridge
-- UE4SS server-side Palworld chat bridge
-- Author: Nexium Labs
--
-- Purpose:
--   Capture normal in-game player chat and forward it to the companion Discord bot.
--   Discord -> Palworld and server administration are handled by the bot via
--   Palworld's official REST API, keeping Discord credentials out of the game process.
--
-- Safety note:
--   Only Sender and Message are read from the chat message struct. Community mods have
--   documented crashes when touching some other chat struct members on dedicated servers.

local MOD_NAME = "NexiumPalBridge"
local MOD_VERSION = "1.0.0"
local PREFIX = "[NexiumPalBridge]"

local function log(message)
    print(string.format("%s %s\n", PREFIX, tostring(message)))
end

local function script_dir()
    local source = debug.getinfo(1, "S").source or ""
    if source:sub(1, 1) == "@" then
        source = source:sub(2)
    end
    return source:match("^(.*[\\/])") or "./"
end

local SCRIPT_DIR = script_dir()
local CONFIG_PATH = SCRIPT_DIR .. "config.lua"
local OUTBOUND_PATH = SCRIPT_DIR .. "bridge-outbound.json"

local ok_config, CONFIG = pcall(dofile, CONFIG_PATH)
if not ok_config or type(CONFIG) ~= "table" then
    log("Failed to load config.lua: " .. tostring(CONFIG))
    return
end

if CONFIG.enabled == false then
    log("Disabled in config.lua")
    return
end

local function debug_log(message)
    if CONFIG.debug then
        log("DEBUG: " .. tostring(message))
    end
end

local function json_escape(value)
    local s = tostring(value or "")
    s = s:gsub("\\", "\\\\")
    s = s:gsub('"', '\\"')
    s = s:gsub("\b", "\\b")
    s = s:gsub("\f", "\\f")
    s = s:gsub("\n", "\\n")
    s = s:gsub("\r", "\\r")
    s = s:gsub("\t", "\\t")
    s = s:gsub("[%z\1-\31]", function(c)
        return string.format("\\u%04x", string.byte(c))
    end)
    return s
end

local function to_string_safe(value)
    if value == nil then return "" end
    local ok, result = pcall(function()
        if type(value) == "string" then return value end
        if value.ToString then return value:ToString() end
        return tostring(value)
    end)
    if ok and result ~= nil then
        return tostring(result)
    end
    return ""
end

local function starts_with_ignored_prefix(message)
    local prefixes = CONFIG.ignored_prefixes or {}
    for _, prefix in ipairs(prefixes) do
        if prefix ~= "" and message:sub(1, #prefix) == prefix then
            return true
        end
    end
    return false
end

local function is_windows()
    return package.config and package.config:sub(1, 1) == "\\"
end

local function curl_binary()
    if CONFIG.curl_binary and CONFIG.curl_binary ~= "" and CONFIG.curl_binary ~= "auto" then
        return CONFIG.curl_binary
    end
    if is_windows() then return "curl.exe" end
    return "curl"
end

local function safe_config_value(value, name, pattern)
    local s = tostring(value or "")
    if s == "" then
        log(name .. " is empty; bridge delivery is disabled")
        return nil
    end
    if pattern and not s:match(pattern) then
        log(name .. " contains unsupported characters; bridge delivery is disabled")
        return nil
    end
    return s
end

-- URL and secret are trusted admin configuration, but we still limit characters because
-- they are passed to the host shell when curl is launched.
local BRIDGE_URL = safe_config_value(
    CONFIG.bridge_url,
    "bridge_url",
    "^[A-Za-z0-9%._~:/%?%[%]@!$&'()*+,;=%-]+$"
)
local BRIDGE_SECRET = safe_config_value(
    CONFIG.bridge_secret,
    "bridge_secret",
    "^[A-Za-z0-9._%-]+$"
)

local queue = {}
local sequence = 0
local worker_started = false

local function build_chat_json(sender, message)
    sequence = sequence + 1
    return string.format(
        '{"version":1,"event":"chat","sequence":%d,"server":"%s","sender":"%s","message":"%s"}',
        sequence,
        json_escape(CONFIG.server_name or "Palworld Server"),
        json_escape(sender),
        json_escape(message)
    )
end

local function enqueue(payload)
    if not BRIDGE_URL or not BRIDGE_SECRET then return end

    -- Prevent an unreachable bridge from growing memory without bound.
    if #queue >= 250 then
        table.remove(queue, 1)
        log("Bridge queue full; dropped oldest event")
    end
    queue[#queue + 1] = payload
end

local function write_payload(payload)
    local file, err = io.open(OUTBOUND_PATH, "wb")
    if not file then
        return false, err
    end
    file:write(payload)
    file:flush()
    file:close()
    return true
end

local function shell_quote(value)
    -- Config values are pre-validated and paths are generated by UE4SS. Double quoting is
    -- enough for the supported simple install paths. Avoid ampersands/quotes in the mod path.
    return '"' .. tostring(value):gsub('"', '') .. '"'
end

local function deliver(payload)
    local ok_write, write_err = write_payload(payload)
    if not ok_write then
        log("Could not write outbound event: " .. tostring(write_err))
        return false
    end

    local timeout = tonumber(CONFIG.request_timeout_seconds) or 4
    if timeout < 1 then timeout = 1 end
    if timeout > 15 then timeout = 15 end

    local null_device = is_windows() and "NUL" or "/dev/null"
    local command = table.concat({
        shell_quote(curl_binary()),
        "--fail-with-body",
        "--silent",
        "--show-error",
        "--max-time", tostring(timeout),
        "--output", null_device,
        "--request POST",
        "--header", shell_quote("Content-Type: application/json"),
        "--header", shell_quote("X-Nexium-Bridge-Key: " .. BRIDGE_SECRET),
        "--data-binary", shell_quote("@" .. OUTBOUND_PATH),
        shell_quote(BRIDGE_URL)
    }, " ")

    debug_log("Delivering bridge event")
    local result = os.execute(command)

    -- Lua versions differ in os.execute return shape. Treat explicit success as success and
    -- otherwise leave the event eligible for a small retry.
    if result == true or result == 0 then
        return true
    end
    return false
end

local function start_worker()
    if worker_started or not BRIDGE_URL or not BRIDGE_SECRET then return end
    worker_started = true

    -- Run network/process work away from the game thread. One event is sent per interval.
    LoopAsync(250, function()
        if #queue == 0 then
            return false
        end

        local item = queue[1]
        if deliver(item.payload) then
            table.remove(queue, 1)
        else
            item.attempts = item.attempts + 1
            if item.attempts >= 3 then
                table.remove(queue, 1)
                log("Dropping bridge event after 3 failed delivery attempts")
            end
        end
        return false
    end)
end

local function on_chat(_, chat_message_param)
    if CONFIG.forward_chat == false then return end

    local ok, err = pcall(function()
        if chat_message_param == nil then return end
        local message_struct = chat_message_param:get()
        if message_struct == nil then return end

        -- Deliberately read only these known-safe properties.
        local message = to_string_safe(message_struct.Message)
        local sender = to_string_safe(message_struct.Sender)

        if message == "" or sender == "" then return end
        if sender:upper() == "SYSTEM" then return end
        if starts_with_ignored_prefix(message) then return end

        enqueue({ payload = build_chat_json(sender, message), attempts = 0 })
    end)

    if not ok then
        log("Chat handler error: " .. tostring(err))
    end
end

local function register_chat_hook()
    local candidates = {
        "/Script/Pal.PalGameStateInGame:BroadcastChatMessage",
        "/Script/Pal.PalGameStateInGame:BroadCastChatMessage",
    }

    for _, path in ipairs(candidates) do
        local ok, pre_id, post_id = pcall(RegisterHook, path, on_chat)
        if ok and pre_id then
            log("Chat hook registered: " .. path)
            return true
        end
        debug_log("Hook candidate unavailable: " .. path .. " (" .. tostring(pre_id) .. ")")
    end

    log("Could not register Palworld chat hook. A game update may have changed the function name.")
    return false
end

log(string.format("%s v%s loading (Author: Nexium Labs)", MOD_NAME, MOD_VERSION))
start_worker()
register_chat_hook()
log("Loaded")
